"""Assemble the final research report from study fragments."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from .experiments import ALL_STUDIES, FRAG, REPORTS, TAB

HEADER = """\
# Pairs trading across asset classes — a walk-forward study

*Generated by the `pairs_trading` research lab in this repository
(`uv run pairs all`). Every table and figure is reproducible offline from the
vendored data; see `research/data/SOURCES.md` for provenance.*

Pairs trading buys one asset and shorts a related one when the spread between
them is unusually wide, betting on convergence. This report tests the classic
cointegration flavor of the strategy — Engle-Granger selection, z-score
entries — on real daily data in five settings: **crypto, US stocks, forex,
commodities, and cross-asset pairs**, with the estimation discipline the
literature demands (walk-forward everything, next-close execution, explicit
costs).

## Methodology

**Spread model.** For legs A and B we fit `ln A = α + β ln B + s` on a
*formation window* and trade the spread `s` over the following *trading
window* (defaults: 252/63 bars, the walk-forward template of Gatev,
Goetzmann & Rouwenhorst 2006). A window is traded only if, on formation data
alone, the pair passes an Engle-Granger cointegration test (MacKinnon
p < 0.05, via `statsmodels.tsa.stattools.coint`) and its spread half-life —
`ln 2 / κ` from the AR(1) fit `Δs_t = a + φ s_{t-1} + ε`, κ = −φ — lies in
[1, 60] bars (the Avellaneda & Lee 2010 style tradability filter). Windows
that fail stay flat but remain in the equity curve (committed capital).

**Signals.** z-score of the spread against a trailing 60-bar mean/std
(strictly causal; a GGR-style variant freezes μ, σ from the formation window).
Enter long (short) the spread at z ≤ −2 (z ≥ +2), exit on reversion through 0,
hard stop at |z| = 4 as a structural-break guard, and force-flat at window
boundaries. After any exit the rule is disarmed until |z| re-enters the entry
band, so a stop is never immediately re-entered.

**Execution and P&L.** The two-leg engine holds `N = equity/(1+β)` dollars of
A against `βN` dollars of B (dollar-neutral in the β-weighted sense, gross =
1× equity), executes on the close one bar *after* the signal (GGR's
"wait one day"; a lag-0 variant quantifies the bounce subsidy), and charges a
per-side proportional cost on every leg's traded notional — 12 bp (crypto),
5 bp (stocks), 2 bp (forex), 5 bp (commodities spot proxies) per side, with
0×/0.5×/2×/4× sweeps. Hedge variants: rolling-OLS (default), formation-frozen,
and a Kalman filter with random-walk (α, β) state (δ = 1e-4, Vₑ = 1e-3, the
E. Chan 2013 reference settings).

**Statistics.** Sharpe annualized at 252 (365 for crypto) periods; Newey-West
HAC t-statistics on mean daily returns (automatic lag rule); the threshold
grids report a Bailey & López de Prado (2014) *deflated Sharpe probability*
that treats every grid cell as a trial. Per-trade economics are reported in bp
of gross notional against the ≈ 4-per-side-bp round-trip hurdle.

**What this design deliberately avoids**: full-sample hedge ratios and
z-parameters (look-ahead), hand-picked famous pairs presented as performance
(each study screens its whole universe mechanically; famous pairs are shown as
labeled case studies), same-bar execution, and cost-free P&L.
"""

CAVEATS = """\
## Limitations and honest caveats

- **Indicative marks, not tradable quotes.** FX fixings (Fed H.10), EIA spot
  assessments and Coin Metrics reference rates are mid-market marks. Spot oil
  and gas are not directly tradable (futures carry roll yield the spot series
  ignores) — commodity results measure statistical structure more than
  bookable P&L.
- **Survivorship.** The S&P 500 panel is the 2018 constituent list projected
  back 5 years, and the crypto panel contains today's major coins; both
  universes omit delisted assets. The featured *pairs* are additionally
  famous ex post — that is exactly why every class also gets a mechanical
  screen and (where the universe is large) a walk-forward portfolio whose
  selections use no hindsight.
- **Shorting is assumed free.** No borrow fees on the short stock leg
  (~25-50 bp/yr for general collateral, worse in squeezes), no crypto margin
  interest or funding, no FX swap points. These subtract roughly 0.3-1 Sharpe
  hundredths to tenths depending on class and exposure.
- **Dividends.** The 5-year equity panel is split- but not dividend-adjusted;
  long/short same-sector pairs offset most, not all, of the effect. The
  1990-2018 panel is fully adjusted.
- **Daily bars only.** The literature (Fil & Kristoufek 2020 for crypto;
  intraday equity studies) finds most surviving pairs alpha at intraday
  horizons, which this dataset cannot reach.
- **Multiple testing.** Even walk-forward results were produced once per
  configuration grid; deflated Sharpe numbers quantify, but cannot eliminate,
  selection effects. Treat |t| < 3 as "not established" (Harvey, Liu & Zhu
  2016).

## References

- Gatev, Goetzmann & Rouwenhorst (2006), *Pairs Trading: Performance of a
  Relative-Value Arbitrage Rule*, RFS 19(3).
- Do & Faff (2010), *Does Simple Pairs Trading Still Work?*, FAJ 66(4); and
  (2012) *Are Pairs Trading Profits Robust to Trading Costs?*, JFR 35(2).
- Vidyamurthy (2004), *Pairs Trading: Quantitative Methods and Analysis*.
- Engle & Granger (1987), *Co-integration and Error Correction*, Econometrica.
- Avellaneda & Lee (2010), *Statistical Arbitrage in the US Equities Market*,
  Quantitative Finance 10(7).
- Chan (2013), *Algorithmic Trading: Winning Strategies and Their Rationale*.
- Clegg (2014), *On the Persistence of Cointegration in Pairs Trading*, SSRN.
- Rad, Low & Faff (2016), *The Profitability of Pairs Trading Strategies*,
  Quantitative Finance 16(10).
- Krauss (2017), *Statistical Arbitrage Pairs Trading Strategies: Review and
  Outlook*, Journal of Economic Surveys 31(2).
- Bailey & López de Prado (2014), *The Deflated Sharpe Ratio*, JPM 40(5).
- Harvey, Liu & Zhu (2016), *…and the Cross-Section of Expected Returns*, RFS.
- Fil & Kristoufek (2020), *Pairs Trading in Cryptocurrency Markets*, IEEE
  Access 8.
"""


def build_report() -> Path:
    """Stitch fragments into research/reports/report.md with an overview table."""
    parts = [HEADER]

    # Cross-class overview from the per-study overview tables
    rows = []
    for study in ALL_STUDIES:
        f = TAB / f'{study}_overview.csv'
        if not f.exists():
            continue
        df = pd.read_csv(f, index_col=0)
        df.insert(0, 'class', study)
        rows.append(df)
    if rows:
        ov = pd.concat(rows)
        cols = ['class', 'sharpe', 'cagr_pct', 'max_dd_pct', 'n_trades',
                'win_rate_pct', 'avg_trade_bp', 'nw_tstat', 'gate_pass_pct',
                'years']
        parts.append('\n## Headline: all featured pairs, out-of-sample\n')
        parts.append(ov[cols].to_markdown(floatfmt='.2f'))
        parts.append('\n*(Walk-forward, default 2σ rule, base costs, next-close '
                     'execution. `gate_pass_pct` = share of windows where the '
                     'formation-period cointegration gate allowed trading.)*\n')

    for study in ALL_STUDIES:
        f = FRAG / f'{study}.md'
        if f.exists():
            parts.append(f.read_text())
    btpy = FRAG / 'zz_btpy.md'
    if btpy.exists():
        parts.append(btpy.read_text())

    parts.append(CAVEATS)
    meta_files = sorted(TAB.glob('*_meta.json'))
    if meta_files:
        stamps = [json.loads(m.read_text()) for m in meta_files]
        parts.append('\n## Reproduction\n')
        parts.append('```\nuv sync\nuv run pairs all        # or: pairs run '
                     '--study crypto|stocks|forex|commodities|cross\nuv run '
                     'pairs report\n```\n')
        parts.append('Study data ranges: ' + '; '.join(
            f"{s['study']} {s['start']}→{s['end']} "
            f"({s['panel_shape'][1]} assets)" for s in stamps) + '.')
    parts.append(f'\n\n*Report generated '
                 f'{datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}.*')
    out = REPORTS / 'report.md'
    out.write_text('\n'.join(parts) + '\n')
    return out
