name: Deploy docs
on:
  push:
    tags: ['[0-9]+.[0-9]+.*']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TQDM_MININTERVAL: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: astral-sh/setup-uv@v6
        with: { enable-cache: true }

      - run: uv sync --python 3.13 --extra doc --extra test

      - run: time uv run doc/build.sh

      - run: .github/deploy-gh-pages.sh
        env:
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
